<a href="https://colab.research.google.com/github/mithhhilesh/DSP-LAB/blob/main/DSP_Lab_2_Numpy_and_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [14]:
type(a)

numpy.ndarray

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# 2D Array
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
c=np.array([[[1,2,3],[2,3,4]],[[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [2 3 4]]

 [[4 5 6]
  [7 8 9]]]


In [20]:
#(from, to, number we want to generate)
np.random.randint(1,13,3)

array([ 9, 11,  8])

In [21]:

# 3x3 array with random int between 0-9

np.random.randint(10, size=(3,3))

array([[8, 1, 0],
       [2, 3, 3],
       [7, 7, 1]])

In [22]:
#bool
np.array([1,2,3,4,5], dtype = bool)

array([ True,  True,  True,  True,  True])

In [23]:
from numpy import *
a = arange(12)
a = a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [24]:
# Transpose Array
trans = np.array([(1,2,3,4), (5,6,7,8)])
trans.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [25]:
trans.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
trans.resize((6,6), refcheck = False)
trans

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [27]:
# return number of elements in arr
arr = np.array([1,2,3,4,5,6,7,9])
arr.size

8

In [28]:
arr2 = np.append(arr,[1,2,3,4])
arr2

array([1, 2, 3, 4, 5, 6, 7, 9, 1, 2, 3, 4])

In [29]:
np.insert(arr2,2,4)

array([1, 2, 4, 3, 4, 5, 6, 7, 9, 1, 2, 3, 4])

In [30]:
arr2 = np.insert(arr2,2,4)

In [31]:
np.delete(trans, 4)

array([1, 2, 3, 4, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
arr = np.array([1,2,3,4])
r = np.add.accumulate(arr)
print(r)

[ 1  3  6 10]


In [33]:
arr = np.array([1,2,3,4])
r = np.multiply.accumulate(arr)
print(r)

[ 1  2  6 24]


In [34]:
arr = np.array([1,2,3,4])
r = np.subtract.accumulate(arr)
print(r)

[ 1 -1 -4 -8]


In [35]:
arr = np.array([1,2,3,4])
r = np.maximum.accumulate(arr)
print(r)

[1 2 3 4]


In [36]:
def hello():
  print("hello guys")

hello()

hello guys


In [37]:
def calculateAvg(a,b):
  return (a+b)/2

calculateAvg(10,20)

15.0

In [38]:
def square(a):
  return a*a

square(10)

100

In [39]:
def student(name, age):
  print(f"Hello {name}, Welcome, your age is", age)

student("Alice", 20)

Hello Alice, Welcome, your age is 20


In [40]:
def fact(num):
  if(num == 0 or num == 1):
    return 1
  else:
    return num*fact(num-1)

fact(5)


120

In [41]:
def sumOfElements(list):
  sum = 0
  for i in range(len(list)):
    sum = sum + i
  return sum
lst = [1,2,3,4,5]
sumOfElements(lst)

10

In [42]:
def fibo(num):
  if(num == 0 or num == 1):
    return num
  else:
    return fibo(num-1) + fibo(num-2)

fibo(5)

5

In [43]:
def calculator(string):
  return eval(string)
calculator("10-20")

-10

In [44]:
def countVowel(string):
  vowel = 0
  for i in range(len(string)):
    if(string[i] == 'a' or string[i] =='e' or string[i] =='i' or string[i] =='o' or string[i] =='u'):
      vowel = vowel + 1
  return vowel

countVowel("hey this is mithilesh i and am alive")

12